spring:
  redis:
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-idle: 10
    lettuce:
      shutdown-timeout: 1000
minio:
  endpoint: http://centos7-16g:9000
  bucket-name: test
  bucket-nodes: 0-9