spring:
  redis:
    jedis:
      pool:
        max-active: 200
        max-idle: 10
    lettuce:
      shutdown-timeout: 1000
    password: 123456
minio:
  endpoint: http://172.25.247.145:9000
  bucket-name: test
  bucket-nodes: 0-9